### PR TITLE
Don't forget the return format

### PR DESCRIPTION
**Pull request by AyzrixYTB**

### CODE REVIEW

**Comment by Steellgold** [comment]
This for PhpStorm IDE, is an error in server ?

**Comment by AyzrixYTB** [comment]
> This for PhpStorm IDE, is an error in server ?

not an error but it's very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very good to use

**Comment by Steellgold** [comment]
ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok

**Comment by AyzrixYTB** [comment]
> ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok ok

So my last message is "push or gay"

**Comment by Steellgold** [comment]
what ?

**Comment by AyzrixYTB** [comment]
> what ?

I have fix conflicts bc conflicts on the flux

**Pull request merged**
